### ISSUE TITLE
效果太惊艳了！！！希望能开发一个betterncm主题

### ISSUE THREAD

**Issue by SteamFinder** [Steve-xmh/mrbncm#1]
歌词页效果太好了，而且性能上也很好
如果能做一个网易云的主题就更好了

**Comment by Steve-xmh** [comment]
这个意见也有人提，不过这里是插件加载器的仓库，可以去 https://github.com/Steve-xmh/applemusic-like-lyrics/issues/67 这里讨论这个插件的建议。
